### ISSUE TITLE
Resolume Arena add feedback support

### ISSUE THREAD

**Issue by theslainman** [bitfocus/companion-module-resolume-arena#1]
**Describe the feature**
Change color on buttons according to OSC output from Resolume

**Is this platform dependent (windows, mac, ..)?**
no

**If documentation is required to implement, do you know where to find it?**
OSC output path are visible inside Resolume

**Usecases**
To get feedback on what clips,layers or columns that are currently active/live

**Comment by DeeJayMX** [comment]
+1

**Comment by hutje** [comment]
There is a possibility with port 12321 but Resolume only supports to send the command to the address with /-separations but to send back information in Companion it is needed to send something like  /bgcolor/<bank>/<page> <R> <G> <B>
For example: /bgcolor/3/2 255 0 255. Only problem is that Resolume doesn't handle spaces in their commands

**Comment by BryanCrotaz** [comment]
Check out #14 - it has support for changing based on layer bypassed and clip connected.

**Comment by gefiltafish22** [comment]
Hello, is there a possibility to have the feedback option (e.g. selected Column 8) to send a command in the Companion to other connections?

**Comment by 4xel** [comment]
merged in #28
