### ISSUE TITLE
could use an upgrade buildout to support new functions of resolume 7

### ISSUE THREAD

**Issue by alstergee** [bitfocus/companion-module-resolume-arena#10]
i wish i was a code guru id definitely help if i had the skillsets, but i would love to see this tool built out properly to support new relative commands, and fix bugs it looks like this hasn't been touched since resolume 6....

**Comment by BryanCrotaz** [comment]
I am rewriting to support the new api. I'll create a PR later today hopefully

**Comment by BryanCrotaz** [comment]
#14, please review and let me know if there are actions or feedbacks that I haven't included that you need

**Comment by 4xel** [comment]
#28 was merged with support for resolume 7, let me know if you are missing functionality
