### ISSUE TITLE
Layer Transition Duration  - shows as % instead of seconds

### ISSUE THREAD

**Issue by pepsijon** [bitfocus/companion-module-resolume-arena#101]
Why is it that the Layer Transition Duration feedback shows as % instead of seconds?

For example, a layer transition duration in Arena that is 0.72s shows in Companion as 72%.

It's confusing when setting / looking at the value that way.

<img width="702" alt="Screenshot 2024-09-29 at 2 12 01 PM" src="https://github.com/user-attachments/assets/15b0df93-bd22-459b-a222-09eee4df9a4c">

**Comment by 4xel** [comment]
fixed in #105
