### ISSUE TITLE
Layer Active Clip Transport Position - MM:SS ?

### ISSUE THREAD

**Issue by pepsijon** [bitfocus/companion-module-resolume-arena#102]
Is it possible to have the option for mm:ss in the Layer Active Clip Transport Position?

All of our clips are well under an hour in length, so it would be nice to see just MM:SS so that it is more readable on a button.  Currently it's either hh:mm:ss or only hh, mm, or ss.  Currently I'm doing it using two buttons, but hate to waste the extra button to do it that way.

**Comment by 4xel** [comment]
added in #104
