### ISSUE TITLE
Bug in Clip Volume

### ISSUE THREAD

**Issue by pepsijon** [bitfocus/companion-module-resolume-arena#109]
In v3.7.0, when using a variable for setting clip volume, the following error occurs:

24.10.10 06:48:41 Instance/Wrapper/Arena: state does not contain a composition: {
    "path": "/parameter/by-id/1728555521863",
    "error": "value is not double"
}

I am trying to use the selected clip variables to set the volume of the selected clip.
$(Arena:selectedClipLayer)
$(Arena:selectedClipColumn)

**Comment by pepsijon** [comment]
Also the + and - still doesn't work for changing clip volume.  The = does work.

And also clip volume feedback isn't working at all now.

**Comment by 4xel** [comment]
Using variables that change is not something that works as of now indeed. Did not know this use-case, will work on fixing this, but will be a lot of work so might take some time.

**Comment by pepsijon** [comment]
Note my other comment regarding - the + / - not working even with direct layer / column numbers (no variables), and also the feedback for clip volume also isn't working either.

**Comment by pepsijon** [comment]
Also - regarding variables... I was using the Arena variables you provided, which I can see changing just fine as a new clip is selected.

**Comment by pepsijon** [comment]
I did some more testing. The Variables DO work just fine, but only with Volume =.
Using + or - does not work whether using variables or direct numbers.  And the volume feedback doesn't work at all.
