### ISSUE TITLE
Not working on Companion 2.2.0

### ISSUE THREAD

**Issue by guimacjr** [bitfocus/companion-module-resolume-arena#11]
This module isn't working on Companion 2.2.0, the connection status is stuck at OK and it won't connect to the resolume at all.

**Comment by Drew-Killeen** [comment]
Sounds like a network configuration issue on your end. I verified that it is still working with the current version of Companion. This module just sends OSC messages to Arena, and so will always display the status as OK even if there is no connection. 

I would try pinging Arena's IP from your device running Companion to make sure your network is allowing them to communicate.

**Comment by BryanCrotaz** [comment]
See #14, feel free to test on the developer version of companion.

Currently not backwards compatible, adding that at the moment.

**Comment by 4xel** [comment]
merged in #28
