### ISSUE TITLE
Selected Clip variables don't work for layers 3 and above

### ISSUE THREAD

**Issue by pepsijon** [bitfocus/companion-module-resolume-arena#112]
Using the following Selected Clip variables only seem to work for Layers 1 and 2.

$(arena:selectedClip)
$(arena:selectedClipColumn)z
$(arena:selectedClipLayer)
$(arena:selectedClipName)

If a clip on Layer 3 or higher is selected, nothing happens (the last values are there, and not updated with the current selection).

Previewed Clip variables work fine on layers 3 and higher however.

**Comment by 4xel** [comment]
In the current version I think this might be caused by you not having a layer feedback present on any button for layer 3. I worked on that in my current work in progress version.

**Comment by pepsijon** [comment]
Once 3.8 shows up in the beta (hasn't yet), I'll try that again.

**Comment by pepsijon** [comment]
v3.8 seems to have fixed this.
