### ISSUE TITLE
Module Randomly Stops Working

### ISSUE THREAD

**Issue by vjshaddow** [bitfocus/companion-module-resolume-arena#115]
im running companion [v3.4.3] and the module is crashing randomly i have to restart companion for it to work again.
if i Disable "Use Rest for web api calls (if false fallback to OSC)" it works fine but obviously feedback features dont work

Starting up module class: ResolumeArenaModuleInstance
error: Error getting config fields: Call timed out
error: Error getting config fields: Call timed out
error: Module registration failed Error: Call timed out
    at IpcWrapper.sendWithCb (C:\companion-module-dev\companion-module-resolume-arena-3.8.0\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:39:30)
    at C:\companion-module-dev\companion-module-resolume-arena-3.8.0\node_modules\@companion-module\base\dist\entrypoint.js:112:20
Starting up module class: ResolumeArenaModuleInstance
error: Error getting config fields: Call timed out
error: Error getting config fields: Call timed out
error: Error getting config fields: Call timed out
error: Module registration failed Error: Call timed out
    at IpcWrapper.sendWithCb (C:\companion-module-dev\companion-module-resolume-arena-3.8.0\node_modules\@companion-module\base\dist\host-api\ipc-wrapper.js:39:30)
    at C:\companion-module-dev\companion-module-resolume-arena-3.8.0\node_modules\@companion-module\base\dist\entrypoint.js:112:20
system: ** Connection crashed **
system: ** Connection stopped **
error: Error getting config field

**Comment by 4xel** [comment]
fixed in https://github.com/bitfocus/companion-module-resolume-arena/releases/tag/v3.9.0
