### ISSUE TITLE
Arena 7 / 6 "Group next column" wrong OSC

### ISSUE THREAD

**Issue by shouweiteoh** [bitfocus/companion-module-resolume-arena#12]
Hi All, 
<img width="557" alt="Screenshot 2022-04-11 at 9 43 13 PM" src="https://user-images.githubusercontent.com/67238979/162753069-a3e9d646-43f2-4723-8062-1b203a450974.png">
 When using composition next column, every increment will get you /composition/columns/4/connect /5/6/7 and goes on, this is good

However, when using
<img width="673" alt="Screenshot 2022-04-11 at 9 43 19 PM" src="https://user-images.githubusercontent.com/67238979/162753290-4f7bcfdc-8178-4a0a-a6bc-9df7a4582738.png">

Group next column, it did not work because i think the OSC is wrong. 

Anyone else has this issue? How can I edit this ?

**Comment by Drew-Killeen** [comment]
Same issue here, the OSC address built into the module is incorrect or outdated. You can still get the same functionality if you do a custom OSC command. The address is /composition/groups/{group-number}/connectnextcolumn. The OSC type flag is integer, and value is 1 regardless of group number.

**Comment by shouweiteoh** [comment]
great, brilliant, thank you !!
