### ISSUE TITLE
V3.9.1: Feedback no longer works

### ISSUE THREAD

**Issue by WillieDaWonka** [bitfocus/companion-module-resolume-arena#120]
As per title, feedbacks no longer work and for the longest time I thought it was on Resolume's end. Commands still work, and certain variables still show up, like `$(Resolume_2:selectedClip)` `$(Resolume_2:selectedClipColumn)` `$(Resolume_2:selectedClipLayer)`. Feedback based on these variables (built-in from module) no longer works and `Layer Active Clip Transport Position` also shows ? instead.

**Comment by 4xel** [comment]
Does it work on the latest stable release? With the same resolume version?

**Comment by WillieDaWonka** [comment]
Sorry! Meant to include that I was on the latest Companion v3.5.0+7607-main-3a772abe and Arena V7.22.0.

Companion Stable Release V3.4.3 and Arena V7.22.0 also doesn't work with V3.9.1 of this module.

**Comment by 4xel** [comment]
Which is the last module version it did work in?

**Comment by 4xel** [comment]
fixed in v3.9.2 #121
