### ISSUE TITLE
Add variable parsing to Custom OSC commands

### ISSUE THREAD

**Issue by NickNeverSleeps** [bitfocus/companion-module-resolume-arena#23]
Would it be possible to add variable parsing to the Custom OSC value so that custom variables can be passed to textblock and other custom OSC endpoints? 

My understanding is that implementation is on a per-module basis and any field can parse for a variable upon filed initialization. Reference of this below.

https://github.com/bitfocus/companion/issues/1248

**Comment by gavalierm** [comment]
+1

**Comment by 4xel** [comment]
This was merged in #33
