### ISSUE TITLE
Input column value over 100

### ISSUE THREAD

**Issue by michaelferris** [bitfocus/companion-module-resolume-arena#25]
Can the restriction of column values less than or equal to 100 be removed? Would love to not have to use custom OSC for simple column triggers.

**Comment by kman1898** [comment]
Really hoping this gets a change sometime soon. Would love to have either no limit or a much higher limit. I just had a show with 250 columns and it took so much time to setup. when all I needed was trigger next column.

**Comment by 4xel** [comment]
pr #30 merged
