### ISSUE TITLE
Master/Slave Functionality

### ISSUE THREAD

**Issue by kman1898** [bitfocus/companion-module-resolume-arena#26]
Is there anyway we could add the ability to connect to multiple IP’s and ports on the same connection? This way building redundant shows we be a lot quicker as you would only need to create one connection and prevent the need for duplication of all actions.

**Comment by kman1898** [comment]
Would this code work? I think what I have here should function correctly but would love a second pair of eyes on it.



import { InstanceBase, Regex, runEntrypoint } from '@companion-module/base'
import { updateActions } from './actions.js'
import { upgrade_v1_0_4 } from './upgrades.js'

class ResolumeArenaInstance extends InstanceBase {
	constructor(internal) {
		super(internal)

		this.updateActions = updateActions.bind(this)
	}

	async configUpdated(config) {
		this.config = config
	}

	async destroy() {
		this.log('debug', 'destroy', this.id)
	}

	getConfigFields() {
		return [
			{
				type: 'textinput',
				id: 'host1',
				label: 'Target IP (Machine 1)',
				tooltip: 'The IP of Resolume for Machine 1',
				width: 6,
				regex: Regex.IP,
			},
			{
				type: 'textinput',
				id: 'port1',
				label: 'Target Port (Machine 1)',
				width: 4,
				default: '7000',
				regex: Regex.PORT,
			},
			{
				type: 'textinput',
				id: 'host2',
				label: 'Target IP (Machine 2)',
				tooltip: 'The IP of Resolume for Machine 2',
				width: 6,
				regex: Regex.IP,
			},
			{
				type: 'textinput',
				id: 'port2',
				label: 'Target Port (Machine 2)',
				width: 4,
				default: '7002',
				regex: Regex.PORT,
			},
		]
	}

	async init(config) {
		this.config = config
		this.groupPos = []
		this.currentCompCol = 0
		this.layerPos = []

		this.updateActions()

		this.updateStatus('ok')
	}

	sendCommand(cmd, arg) {
		let host, port;

		if (cmd && this.config.host1 !== undefined && this.config.port1 !== undefined) {
			this.log('debug', `Sending command to Machine 1: ${cmd} ${arg?.value}`)
			host = this.config.host1;
			port = this.config.port1;
		} else if (cmd && this.config.host2 !== undefined && this.config.port2 !== undefined) {
			this.log('debug', `Sending command to Machine 2: ${cmd} ${arg?.value}`)
			host = this.config.host2;
			port = this.config.port2;
		} else {
			this.log('debug', `Host, port, or command not defined: ${cmd}`)
			return;
		}

		this.oscSend(host, port, cmd, [arg]);
	}
}

runEntrypoint(ResolumeArenaInstance, [upgrade_v1_0_4])

**Comment by dnmeid** [comment]
You code would not work. It would always send only to host1.
Besides that, you can tweak your Companion and modules on your machine like you want, but supporting more than one host from one connection is not what we want as a general procedure.
