### ISSUE TITLE
I would love to add these functions but I don't know if the logic would even work?

### ISSUE THREAD

**Issue by kman1898** [bitfocus/companion-module-resolume-arena#27]
import { Fields } from './setup.js';

export function updateActions() {
    this.setActionDefinitions({
        triggerClip: {
            name: 'Start Clip',
            options: [Fields.Layer(), Fields.Column()],
            callback: ({ options }) => {
                let arg = {
                    type: 'i',
                    value: parseInt(1),
                };
                this.sendCommand(`/composition/layers/${options.layer}/clips/${options.column}/connect`, arg);
            },
        },
        // ... (existing actions)

        adjustClipSpeed: {
            name: 'Adjust Clip Speed',
            options: [Fields.Layer(), Fields.Column()],
            callback: ({ options }) => {
                let speedValue = Math.random() * 10;
                let arg = {
                    type: 'f',
                    value: speedValue,
                };
                this.sendCommand(`/composition/layers/${options.layer}/clips/${options.column}/transport/position/behaviour/speed`, arg);
            },
        },

        changeCompositionSpeed: {
            name: 'Change Composition Speed',
            options: [],
            callback: () => {
                let speedValue = Math.random() * 10;
                let arg = {
                    type: 'f',
                    value: speedValue,
                };
                this.sendCommand(`/composition/speed`, arg);
            },
        },

        changeGroupSpeed: {
            name: 'Change Group Speed',
            options: [Fields.Group()],
            callback: ({ options }) => {
                let speedValue = Math.random() * 10;
                let arg = {
                    type: 'f',
                    value: speedValue,
                };
                this.sendCommand(`/composition/groups/${options.group}/speed`, arg);
            },
        },

        controlCompositionTransport: {
            name: 'Control Composition Transport',
            options: [],
            callback: ({ options }) => {
                // Implement your logic to control composition transport
                // You can use options like '/composition/forwards', '/composition/paused', '/composition/backwards'
                // and send the corresponding OSC commands
            },
        },

        controlGroupTransport: {
            name: 'Control Group Transport',
            options: [Fields.Group()],
            callback: ({ options }) => {
                // Implement your logic to control group transport
                // You can use options like `/composition/groups/${options.group}/forwards`, `/composition/groups/${options.group}/paused`, `/composition/groups/${options.group}/backwards`
                // and send the corresponding OSC commands
            },
        },

        controlLayerTransport: {
            name: 'Control Layer Transport',
            options: [Fields.Layer(), Fields.Column()],
            callback: ({ options }) => {
                // Implement your logic to control layer transport
                // You can use options like `/composition/layers/${options.layer}/clips/${options.column}/transport/position/behaviour/playdirection`
                // and send the corresponding OSC commands
            },
        },

        adjustCompositionOpacity: {
            name: 'Adjust Composition Opacity',
            options: [],
            callback: () => {
                let opacityValue = Math.random();
                let arg = {
                    type: 'f',
                    value: opacityValue,
                };
                this.sendCommand(`/composition/master`, arg);
            },
        },

        adjustGroupOpacity: {
            name: 'Adjust Group Opacity',
            options: [Fields.Group()],
            callback: ({ options }) => {
                let opacityValue = Math.random();
                let arg = {
                    type: 'f',
                    value: opacityValue,
                };
                this.sendCommand(`/composition/groups/${options.group}/video/opacity`, arg);
            },
        },

        adjustLayerOpacity: {
            name: 'Adjust Layer Opacity',
            options: [Fields.Layer(), Fields.Column()],
            callback: ({ options }) => {
                let opacityValue = Math.random();
                let arg = {
                    type: 'f',
                    value: opacityValue,
                };
                this.sendCommand(`/composition/layers/${options.layer}/video/opacity`, arg);
            },
        },

        // ... (other actions)
    });
}

**Comment by dnmeid** [comment]
Please use pull requests for pull requests.

**Comment by 4xel** [comment]
These are interesting actions

- adjustClipSpeed
- changeCompositionSpeed
- changeGroupSpeed
- controlCompositionTransport
- controlGroupTransport
- controlLayerTransport
- adjustCompositionOpacity
- adjustGroupOpacity
- adjustLayerOpacity

Will create a new issue with the feature request

**Comment by 4xel** [comment]
#35
