### ISSUE TITLE
Layer Group Column Trigger

### ISSUE THREAD

**Issue by kman1898** [bitfocus/companion-module-resolume-arena#36]
So you have trigger clip and start column but you should add a start group. Also I think making them the same name either trigger or start column/group/clip

**Comment by 4xel** [comment]
Do you want a "trigger column in group" action?
<img width="659" alt="Screenshot 2024-02-12 at 20 40 41" src="https://github.com/bitfocus/companion-module-resolume-arena/assets/10220112/f0f3a0ad-8433-44b7-b9bc-7d76dbe2be88">

**Comment by 4xel** [comment]
Merged in #38
