### ISSUE TITLE
Time Remaining

### ISSUE THREAD

**Issue by kman1898** [bitfocus/companion-module-resolume-arena#37]
Would love to see a time remaining feedback if at all possible

**Comment by 4xel** [comment]
I saw this in "stageTimer.io"
<img width="271" alt="image" src="https://github.com/bitfocus/companion-module-resolume-arena/assets/10220112/9614e9d6-a30c-49d5-bc52-f8b493eb1387">
Would you also like these options?

**Comment by kman1898** [comment]
Yes these would be fantastic!

**Comment by kman1898** [comment]
So I want it for specific clip but also could be useful for selected clip

**Comment by 4xel** [comment]
Also for active clip on a layer

**Comment by 4xel** [comment]
![timer](https://github.com/bitfocus/companion-module-resolume-arena/assets/10220112/5d4bac42-e72f-4897-9429-feda757c9c7b)
<img width="1053" alt="image" src="https://github.com/bitfocus/companion-module-resolume-arena/assets/10220112/b025b882-b251-4ca1-b33c-564c7713636d">
