### ISSUE TITLE
option to set the thumbnail aspect ratio

### ISSUE THREAD

**Issue by 4xel** [bitfocus/companion-module-resolume-arena#50]
would be nice if we had the option to set the thumbnail aspect ratio. right now the image shows letterbox, would be nice to make the image cover the entire button.
<img width="237" alt="Screenshot 2024-02-18 184331" src="https://github.com/bitfocus/companion-module-resolume-arena/assets/141574914/8f52451c-4f8b-4f9b-92e0-ca4d62ccd13e">

_Originally posted by @vjshaddow in https://github.com/bitfocus/companion-module-resolume-arena/issues/35#issuecomment-1951487187_

**Comment by vjshaddow** [comment]
did some more tests and the thumbnail does have the form of the content unless you upload a custom thumbnail but doing that for each clip is not feasible. i did noticed however that if the content itself is square it wont go full screen like a standard companion button would which in a way is good because if we add the Connected Clip feedback it will change the color of the outline like shown in the attached image
![resolumefindings](https://github.com/bitfocus/companion-module-resolume-arena/assets/141574914/3d10043c-0230-418f-a79b-8467018aa18b)

**Comment by kman1898** [comment]
I would actually prefer the last option 3:4

**Comment by vjshaddow** [comment]
> @vjshaddow what do you mean by: "build in companion png image cover"? Are these available companion options? I can't find them if that's the case

this is just a reference how loading a thumbnail in companion fills the frame if its square

<img width="79" alt="image" src="https://github.com/bitfocus/companion-module-resolume-arena/assets/141574914/2ccd3965-3d9c-4ae7-bfb5-dbfa2d52bbbb">

**Comment by 4xel** [comment]
@vjshaddow how do you like this?
<img width="339" alt="image" src="https://github.com/bitfocus/companion-module-resolume-arena/assets/10220112/679c0740-ab58-498a-a816-16592cb5ee62">

**Comment by vjshaddow** [comment]
> @vjshaddow how do you like this? <img alt="image" width="339" src="https://private-user-images.githubusercontent.com/10220112/306771715-679c0740-ab58-498a-a816-16592cb5ee62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2NzIzMzQsIm5iZiI6MTcwODY3MjAzNCwicGF0aCI6Ii8xMDIyMDExMi8zMDY3NzE3MTUtNjc5YzA3NDAtYWI1OC00OThhLWE4MTYtMTY1OTJjYjVlZTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDA3MDcxNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWEwN2Y2ZTQzOWZmZDU0MjQyNDFiMDRhN2RjYTE5NTkxNGFjNTY5YTI1ODdhYmRkMDg2NmE3ZDk0ZDljZjE4ODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.VsluYs3hKfUGwo5VlM1pZHWsYIrmKQ4jZStJixuGer0">

this looks great

**Comment by 4xel** [comment]
merged in #63
