### ISSUE TITLE
custom osc error

### ISSUE THREAD

**Issue by jun-cmd1** [bitfocus/companion-module-resolume-arena#6]

**Comment by DeeJayMX** [comment]
Unable to write custom osc command
tried to put /composition/bypassed
command don't send and companion freeze, I got a JAVA error and have to click ok

**Comment by DeeJayMX** [comment]
![image](https://user-images.githubusercontent.com/36418772/72906314-514ecf80-3d32-11ea-9f24-af911d1bdb98.png)

**Comment by PDNerd** [comment]
Same exact issue. Windows 10, Companion 2.0. When this works correctly the entire Resolume community will be stoked. There are hundreds of OSC commands.

**Comment by escii** [comment]
Is there any chance to get this error fixed?
Custom OSC Commands for Resolume not working on Windows 10, Companion 2.1
Shows a 'writer' undefined error ;(

**Comment by themediaguy1297** [comment]
Is there a timeline for when this will get fixed?

**Comment by JeffreyDavidsz** [comment]
Fixed in last build
