### ISSUE TITLE
relative commands

### ISSUE THREAD

**Issue by alstergee** [bitfocus/companion-module-resolume-arena#8]
i need a button to support resolumes relative commands, ie 

i want a buttong to advance the x axis by +1 every time i push it

resolume claims you can add a "+" 1 but it doesnt seem to translate into companion appropreately

**Comment by alstergee** [comment]
For instance, you can use a "+", "-", or "*" to respectively add, subtract or multiply the current value with the incoming one:

/composition/layers/1/video/opacity "+" 0.2

Will increase the opacity of layer one by 20%.

**Comment by 4xel** [comment]
https://resolume.com/forum/viewtopic.php?t=21959 This will only work for Intergers due to a resolume bug.
But I create a PR for this: #31

**Comment by 4xel** [comment]
#31 is Merged
