### ISSUE TITLE
Actions stayed "clicked"

### ISSUE THREAD

**Issue by thormug** [bitfocus/companion-module-resolume-arena#83]
When you trigger an action with this module, only one action is sent with an integer parameter of 1.

But the way Resolume work is 1 is to press the button corresponding to the action, and 0 is for releasing it.
By sending only a 1, the button is the GUI of Resolume stay clicked forever, which can lead to strange things.

For example : 

Using companion, send a simple "arena: Trigger Clip" Layer 1 Column 1
--> The clip start playing.
Send a "arena: Clear Layer" Layer 1
--> The clip stop playing
In the Resolume GUI, click on the clip
--> Nothing happen
Click a second time
--> The clip start playing

Because for Resolume, you never released the key so it was only released when you clicked on the GUI the first time, so it can register the second click.

For every action corresponding to a "key press" (and it seems to be the same either in OSC and REST), you need to send an integer of 0 a few milliseconds after sending an integer of 1 in order to "create a complete key press"

Workaround : 
Create everything using custom OSC commands, and sending 2 actions at a few milliseconds interval.

**Comment by thormug** [comment]
The action "Clear Layer" is doing it correctly 
https://github.com/bitfocus/companion-module-resolume-arena/blob/master/src/arena-api/osc.ts#L47

But the action "Connect Clip" (and many others) is not
https://github.com/bitfocus/companion-module-resolume-arena/blob/master/src/arena-api/osc.ts#L39

**Comment by 4xel** [comment]
merged
