### ISSUE TITLE
Next/Previous column without number as default?

### ISSUE THREAD

**Issue by Haavard15** [bitfocus/companion-module-resolume-arena#94]
Hey all,

I'm not a very advanced Resolume user, but I just had a show error because of this:

https://github.com/bitfocus/companion-module-resolume-arena/blob/82e5e959544ad7e93442c7c188c0e4b005272a25/src/arena-api/osc.ts#L112-L119

Doesnt it make more sense to use the OSC command `/composition/connectnextcolumn`?

Same for backwards, `/composition/connectprevcolumn`

**Comment by 4xel** [comment]
merged in #96
